### ISSUE TITLE
llama-cpp-python-cuda wheel

### ISSUE THREAD

**Issue by x90skysn3k** [jllllll/llama-cpp-python-cuBLAS-wheels#1]
Is it possible to get a `llama-cpp-python-cuda` wheel compiled with AVX2=OFF, F16C=OFF, FMA=OFF? I'm running on an E5-2697v2 with text-generation-webui and i'm getting illegal instructions because my CPU does not support AVX2 or FMA.

**Comment by jllllll** [comment]
Yes. I was planning on adding this sometime today.

**Comment by x90skysn3k** [comment]
that would be awesome, been having illegal instructions due to my older processor.

**Comment by x90skysn3k** [comment]
it'd be great to have them for webui under the different namespace of llama_cpp_cuda with cuBLAS support with the  AVX2=OFF, F16C=OFF, FMA=OFF.

**Comment by jllllll** [comment]
Wheels have been built for CPU-only packages and cuBLAS packages:
```
python -m pip install llama-cpp-python llama-cpp-python-cuda --force-reinstall --no-deps --index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/basic/cpu --extra-index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/textgen/basic/cu117
```
Let me know if there are any issues.
