### ISSUE TITLE
Add support for METAL wheels (MacOS)

### ISSUE THREAD

**Issue by gaby** [jllllll/llama-cpp-python-cuBLAS-wheels#10]
Hello @jllllll I remember you adding some test workflows for MacOS but they seem to be gone. Any plans to add wheels for `metal` support?

**Comment by jllllll** [comment]
I'm planning on it.
The test workflows I had before can't work with llama-cpp-python 0.2.0+, so I removed them until I have time to do some more thorough testing for it.

I was originally planning on making `universal2` wheels for it to simplify building, distribution and installation.
However, changes in llama-cpp-python's `CMakeLists.txt` necessitate building separate wheels for x64 and ARM.

**Comment by gaby** [comment]
@jllllll Cool! Yeah i have noticed quite a bit of changes since v0.2.x release on the workflows. Thanks for the info

**Comment by jllllll** [comment]
Added wheels for MacOS here: https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/tag/metal

Let me know if there are any issues.

**Comment by gaby** [comment]
@jllllll Thank you! Really appreciate it :D
