### ISSUE TITLE
RK3588 arm64 processor

### ISSUE THREAD

**Issue by bluciano212** [jllllll/llama-cpp-python-cuBLAS-wheels#16]
Hi , can I install this llama-cpp-python-cuBLAS-wheels on 
orange pi 5 , (arm64  processor) with ARMBIAN 23.8.3 jammy 64 bit GNOME version 42.9 
I have:  
AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 0 | VSX = 0 |

**Comment by jllllll** [comment]
I don't currently have any Linux arm64 wheels. Additionally, I don't think you can run CUDA on orange pi 5. So, there isn't much reason to use the wheels in this repo anyway.

Building llama-cpp-python yourself on your orange pi 5 is your best option for this as far as I can tell.
I'll start building Linux arm64 wheels eventually, but there is no guarantee that they will work on orange pi 5.
