### ISSUE TITLE
GGUF Support

### ISSUE THREAD

**Issue by sammcj** [jllllll/llama-cpp-python-cuBLAS-wheels#3]
Howdy,

GGUF support has now been [merged into llama-cpp-python](https://github.com/abetlen/llama-cpp-python/issues/628), I believe this project might need a new release to add the support in.

(related to https://github.com/oobabooga/text-generation-webui/issues/3676)

**Comment by jllllll** [comment]
Yeah, I know. Been building wheels for the past 5 hours. Github's runners seem to be somewhat slower than usual lately.

One thing to keep in mind with this, is that llama-cpp-python will no longer support GGML and only support GGUF.
Another thing to note is that ctransformers has already been updated in the webui with GGUF support.

Regardless, wheels will be uploaded soon.

**Comment by sammcj** [comment]
ohhh I just saw the actions tab and that you've been rate limited 😅 , thanks, appreciate your work!
