### ISSUE TITLE
Expand README with workflows usage

### ISSUE THREAD

**Issue by gaby** [jllllll/llama-cpp-python-cuBLAS-wheels#4]
Hello @jllllll could you add a section on the README that explains what is the purpose of each workflow file?

For example: I'm trying to build wheels for amd64/arm64, py3.11 only, and each CPU/GPU option. There's several workflows that are pointing to the same thing, I can't tell which one to use.

Thanks!

**Comment by jllllll** [comment]
I will work on this, but it may take a bit. I'll likely add this info to a separate doc so as to not clutter the main README.

**Comment by gaby** [comment]
@jllllll Sure that works, i'm just not sure which Workflow to trigger to build which wheels 😂

**Comment by jllllll** [comment]
Uploaded a file with explanations of all the workflows: [workflows.md](https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/blob/main/workflows.md)

If I need to add anything to it, let me know.

**Comment by jllllll** [comment]
For your specific case, you will likely want to make a copy of one of the workflows and limit it's job matrices to just build the wheels you want.

**Comment by gaby** [comment]
@jllllll Thank you, really appreciate it!
